baseURL = 'https://blog.bromo.art.br/'
languageCode = 'pt'
title = 'Bromo Blog'
theme = 'BromaticTheme'

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"